using Cysharp.Threading.Tasks;
using DC;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ï¿½ï¿½ï¿½IObjectï¿½Ìï¿½ï¿½Wï¿½Ç—ï¿½
/// </summary>
public class RTCObject : MonoBehaviour
{
    // Object Data
    public bool isLocal = false;
    [System.NonSerialized] public string objId = "";
    public string ownerId = "";
    public string cid = "";
    public string objType = "human";    // TODO: ï¿½Ê‚ÌêŠï¿½Åİ’è‚·ï¿½×‚ï¿½
    public float syncIntervalTimeSecond = 0.1f; // ï¿½Åï¿½ï¿½lï¿½ï¿½İ’è‚µï¿½Ä‚ï¿½ï¿½ï¿½
    public int syncDistance = 0;

    public string nametag
    {
        get => _nametag;
        set
        {
            _nametag = value;
            // nameTag?.SetName(value);
            if (!isLocal) return;

            // ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡ï¿½ÍAï¿½Sï¿½ï¿½ï¿½É‘ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
            var sendData = new Dictionary<string, object>()
            {
                { "type","changeNametag" },
                { "objId", objId },
                { "nametag",value },
            };
            GM.Msg("RTCSendAll", sendData);
        }
    }
    [SerializeField] string _nametag = "";
    RTCNameTag nameTag;

    // -----------------------------------
    // Sync Data
    protected Dictionary<string, object> locationData = new();

    // -----------------------------------
    // Send
    float time = 0;
    Vector3 previousPosition = Vector3.zero;
    Quaternion previousRotation = Quaternion.identity;

    // -----------------------------------
    // Recieve
    [SerializeField] float interpolationSpeed = 2.0f;
    Vector3 recievedPosition = Vector3.zero;
    Quaternion recievedRotation = Quaternion.identity;

    Vector3 currentPosition = Vector3.zero;
    Quaternion currentRotation = Quaternion.identity;

    /// <summary>
    /// ï¿½ï¿½ï¿½Û‚Ìï¿½ï¿½ÔH
    /// </summary>
    float elapsedTime = 0;
    private Transform content;

    // -----------------------------------
    // Humanoid
    public Animator animator;
    public RTCAnimator rtcAniamtor;

    // StarterAssets.StarterAssetsInputs starterAssets;

    // -----------------------------------
    private void Awake()
    {
        if (objType == "human")
        {
            // ï¿½lï¿½^ï¿½ï¿½Objectï¿½Å‚ï¿½ï¿½ï¿½ÎAGeometryï¿½Éİ’è‚·ï¿½ï¿½
            content = transform.Find("Geometry");
            // TryGetComponent(out animator);
            TryGetComponent(out nameTag);
            if(!TryGetComponent(out rtcAniamtor))
            {
                Debug.LogError("RTCAnimatorï¿½ï¿½ï¿½ï¿½ï¿½İ‚ï¿½ï¿½È‚ï¿½");
            }
        }
        else
        {
            // ï¿½qï¿½Kï¿½wï¿½ï¿½Objectï¿½İ’uï¿½ÌêŠï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
            GameObject content = new GameObject("content");
            content.transform.SetParent(transform);
            this.content = content.transform;
            content.transform.ResetTransform();
        }
    }

    private void Start()
    {
        if (!isLocal) return;

        SetData();
    }

    private void Update()
    {
        if (isLocal)
        {
            UpdataLocation();
        }
        else
        {
            InterpolationLocation();
        }
    }

    /// <summary>
    /// Localï¿½Ìê‡ï¿½ADataï¿½ï¿½İ’è‚·ï¿½ï¿½
    /// </summary>
    public void SetData()
    {
        isLocal = true;
        PrepareSendLocationData();
        objId = Guid.NewGuid().ToString("N");
        locationData["objId"] = objId;
        ownerId = GM.db.rtc.id;
        gameObject.name = $"{name}-{objId}";

        var tag = GM.Msg<object>("GetSaveData", "nametag");
        if (tag != null)
        {
            nametag = tag.ToString();
        }

        GM.Msg("AddSyncObject", this);
    }

    /// <summary>
    /// Remote
    /// </summary>
    /// <param name="objId"></param>
    /// <param name="cid"></param>
    /// <param name="position"></param>
    /// <param name="rotation"></param>
    public void SetData(string id, string objId, string cid, string objType, Vector3 position, Vector3 rotation)
    {
        this.ownerId = id;
        this.objId = objId;
        this.cid = cid;
        this.objType = objType;
        isLocal = false;
        transform.position = position;
        transform.rotation = Quaternion.Euler(rotation);
        gameObject.name = $"{name}-{objId}";
    }

    /// <summary>
    /// Dataï¿½ğ‘—Mï¿½ï¿½ï¿½é€ï¿½ï¿½
    /// </summary>
    void PrepareSendLocationData()
    {
        locationData.Add("objId", "");
        locationData.Add("type", "location");
        locationData.Add("position", transform.position.ToSplitString());
        locationData.Add("rotation", transform.rotation.eulerAngles.ToSplitString());
    }

    /// <summary>
    /// Prepare Send Data
    /// </summary>
    void UpdataLocation()
    {
        // ï¿½ï¿½ï¿½Mï¿½ÔŠu
        time += Time.deltaTime;
        if (time < syncIntervalTimeSecond) return;
        time = 0;

        // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Ï‚ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½ÍAï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½È‚ï¿½
        if (previousPosition == transform.position &&
            previousRotation == transform.rotation) return; 

        // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Ù‚È‚ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
        previousPosition = transform.position;
        transform.rotation = transform.rotation;

        locationData["position"] = transform.position.ToSplitString();
        locationData["rotation"] = transform.rotation.eulerAngles.ToSplitString();

        // ï¿½ï¿½ï¿½Â‚Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ğ‘—‚ï¿½ï¿½æ‚¤ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        GM.Msg("SetSelfLocationData", locationData);
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="data"></param>
    public void ReceiveLocation(Dictionary<string, object> data)
    {
        recievedPosition = data["position"].ToString().ToVector3();
        recievedRotation = Quaternion.Euler(data["rotation"].ToString().ToVector3());
        syncIntervalTimeSecond = float.Parse(data["time"].ToString());
        currentPosition = transform.position;
        currentRotation = transform.rotation;
        elapsedTime = 0;
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½Wï¿½Ì•ï¿½ï¿½
    /// </summary>
    void InterpolationLocation()
    {
        var t = elapsedTime / syncIntervalTimeSecond; // TODO: syncIntervalTimeSecondï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½Kï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        elapsedTime += Time.deltaTime;
        transform.position = Vector3.LerpUnclamped(currentPosition, recievedPosition, t);
        transform.rotation = Quaternion.LerpUnclamped(currentRotation, recievedRotation, t);
        GM.Msg("UpdateDistance", ownerId, recievedPosition);
        //if (objType != "human") return;
        //var speed = (currentPosition - transform.position).magnitude;
    }

    /// <summary>
    /// TODO: ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ğ‘—Mï¿½ï¿½ï¿½é‚©ï¿½ÌŒï¿½ï¿½è‚ªï¿½Kï¿½v
    /// </summary>
    /// <param name="path"></param>
    public async void SetObject(string path)
    {
        var avatarObj = GM.Msg<GameObject>("LoadAvatar", path);
        SetContent(avatarObj.transform);

        // IPFSï¿½Ö‚ï¿½Upload
        var cid = await GM.Msg<UniTask<string>>("UploadAvatar", path);
        this.cid = cid;
        GM.db.user.users[GM.db.rtc.id].cid = cid;

        // ï¿½Sï¿½Ì‚Ö‚Ì’Ê’m
        var sendData = new Dictionary<string, object>()
        {
            { "type", "change" },
            { "objId",  objId },
            { "objType",  objType },
            { "cid", cid },
        };
        GM.Msg("RTCSendAll", sendData);
    }

    /// <summary>
    /// Avatarï¿½ï¿½ï¿½ï¿½İ’è‚·ï¿½ï¿½
    /// </summary>
    /// <param name="obj"></param>
    public async void SetContent(Transform obj)
    {
        content.DestroyChildren();
        obj.SetParent(content);
        obj.ResetTransform();

        await UniTask.Yield();
        animator?.Rebind();
        animator?.Update(0f);
    }
}
