using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using DC;
using UnityEngine;

/// <summary>
/// ï¿½ï¿½ï¿½IObjectï¿½Ìï¿½ï¿½Wï¿½Ç—ï¿½
/// </summary>
public class RTCObjectSync : MonoBehaviour
{
    // Object Data
    public bool isLocal = false;
    public string ownerId = "";
    public string objId = "";
    public string cid = "";
    public string objType = "human";    // TODO: ï¿½Ê‚ÌêŠï¿½Åİ’è‚·ï¿½×‚ï¿½
    public float syncIntervalTimeSecond = 0.1f; // ï¿½Åï¿½ï¿½lï¿½ï¿½İ’è‚µï¿½Ä‚ï¿½ï¿½ï¿½
    public int syncDistance = 0;

    public string nametag
    {
        get => _nametag;
        set
        {
            _nametag = value;
            nameTag?.SetName(value);
            if (!isLocal) return;

            // ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Ìê‡ï¿½ÍAï¿½Sï¿½ï¿½ï¿½É‘ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
            var sendData = new Dictionary<string, object>()
            {
                { "type","changeNametag" },
                { "objId", objId },
                { "nametag",value },
            };
            GM.Msg("RPCSendAll", sendData);
        }
    }
    [SerializeField] string _nametag = "";
    public RTCNameTag nameTag;

    // -----------------------------------
    // Sync Data
    protected P_Location locationData = new();

    // -----------------------------------
    // Send
    float time = 0;
    Vector3 previousPosition = Vector3.zero;
    Quaternion previousRotation = Quaternion.identity;

    // -----------------------------------
    // Recieve
    [SerializeField] float interpolationSpeed = 2.0f;
    Vector3 recievedPosition = Vector3.zero;
    Quaternion recievedRotation = Quaternion.identity;

    Vector3 currentPosition = Vector3.zero;
    Quaternion currentRotation = Quaternion.identity;

    /// <summary>
    /// ï¿½ï¿½ï¿½Û‚Ìï¿½ï¿½ÔH
    /// </summary>
    float elapsedTime = 0;
    private Transform content;

    // -----------------------------------
    // Humanoid
    public Animator animator;
    public RTCAnimator rtcAniamtor;

    // -----------------------------------
    public Action InitMethod;

    // StarterAssets.StarterAssetsInputs starterAssets;

    // -----------------------------------
    private void Awake()
    {
        if (objType == "human")
        {
            // ï¿½lï¿½^ï¿½ï¿½Objectï¿½Å‚ï¿½ï¿½ï¿½ÎAGeometryï¿½Éİ’è‚·ï¿½ï¿½
            content = transform.Find("Geometry");
            // TryGetComponent(out animator);
            TryGetComponent(out nameTag);
            if(!TryGetComponent(out rtcAniamtor))
            {
                Debug.LogError("RTCAnimatorï¿½ï¿½ï¿½ï¿½ï¿½İ‚ï¿½ï¿½È‚ï¿½");
            }
        }
        else
        {
            // ï¿½qï¿½Kï¿½wï¿½ï¿½Objectï¿½İ’uï¿½ÌêŠï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
            GameObject content = new GameObject("content");
            content.transform.SetParent(transform);
            this.content = content.transform;
            content.transform.ResetTransform();
        }

        if (isLocal)
        {
            SetLocalData();
        }
    }

    private void Update()
    {
        if (isLocal)
        {
            UpdataLocation();
        }
        else
        {
            InterpolationLocation();
        }
    }

    /// <summary>
    /// Localï¿½Ìê‡ï¿½ADataï¿½ï¿½İ’è‚·ï¿½ï¿½
    /// </summary>
    public void SetLocalData()
    {

        isLocal = true;
        PrepareSendLocationData();
        objId = Guid.NewGuid().ToString("N");
        locationData.objId = objId;
        ownerId = GM.db.rtc.id;
        gameObject.name = $"{name}-{objId}";

        var tag = GM.Msg<object>("GetSaveData", "nametag");
        if (tag != null)
        {
            nametag = tag.ToString();
        }

        GM.Msg("AddSyncObject", this);
        InitMethod?.Invoke();
    }

    /// <summary>
    /// Remote
    /// </summary>
    /// <param name="objId"></param>
    /// <param name="cid"></param>
    /// <param name="position"></param>
    /// <param name="rotation"></param>
    public void SetData(string ownerId, P_ObjectInfoResponse data)
    {
        this.ownerId = ownerId;
        this.objId = data.objId;
        this.cid = data.cid;
        // this.objType = objType;
        isLocal = false;
        transform.position = data.position;
        transform.rotation = Quaternion.Euler(data.rotation);
        gameObject.name = data.objName;
    }

    /// <summary>
    /// Dataï¿½ğ‘—Mï¿½ï¿½ï¿½é€ï¿½ï¿½
    /// </summary>
    void PrepareSendLocationData()
    {
        locationData.objId = "";
        locationData.position = transform.position;
        locationData.rotation = transform.rotation.eulerAngles;
    }

    /// <summary>
    /// Prepare Send Data
    /// </summary>
    void UpdataLocation()
    {
<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // é€ä¿¡é–“éš”
=======
        // ï¿½ï¿½ï¿½Mï¿½ÔŠu
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        time += Time.deltaTime;
        if (time < syncIntervalTimeSecond) return;
        time = 0;

<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // åº§æ¨™ãŒå¤‰ã‚ã£ã¦ã„ãªã„å ´åˆã¯ã€é€ä¿¡ã—ãªã„
=======
        // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Ï‚ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½ÍAï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½È‚ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        if (previousPosition == transform.position &&
            previousRotation == transform.rotation) return;

<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // åº§æ¨™ãŒç•°ãªã‚‹å ´åˆã€é€ä¿¡ã™ã‚‹
=======
        // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Ù‚È‚ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        previousPosition = transform.position;
        transform.rotation = transform.rotation;

        locationData.position = transform.position;
        locationData.rotation = transform.rotation.eulerAngles;

<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // ã„ã¤ã§ã‚‚è‡ªåˆ†ã®æƒ…å ±ã‚’é€ã‚Œã‚‹ã‚ˆã†ã«æº–å‚™ã—ã¦ãŠã
=======
        // ï¿½ï¿½ï¿½Â‚Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ğ‘—‚ï¿½ï¿½æ‚¤ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        GM.Msg("SetSelfLocationData", locationData);
    }

    /// <summary>
<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
    /// åº§æ¨™ã‚’å—ä¿¡ã™ã‚‹
=======
    /// ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
    /// </summary>
    /// <param name="data"></param>
    public void ReceiveLocation(P_Location data)
    {
        recievedPosition = data.position;
        recievedRotation = Quaternion.Euler(data.rotation);
        // syncIntervalTimeSecond = data.time;
        currentPosition = transform.position;
        currentRotation = transform.rotation;
        elapsedTime = 0;
    }

    /// <summary>
<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
    /// åº§æ¨™ã®è£œé–“
    /// </summary>
    void InterpolationLocation()
    {
        var t = elapsedTime / syncIntervalTimeSecond; // TODO: syncIntervalTimeSecondã‚’å¤–éƒ¨ã‹ã‚‰å–å¾—ã™ã‚‹å¿…è¦ãŒã‚ã‚‹
=======
    /// ï¿½ï¿½ï¿½Wï¿½Ì•ï¿½ï¿½
    /// </summary>
    void InterpolationLocation()
    {
        var t = elapsedTime / syncIntervalTimeSecond; // TODO: syncIntervalTimeSecondï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½Kï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        elapsedTime += Time.deltaTime;
        transform.position = Vector3.LerpUnclamped(currentPosition, recievedPosition, t);
        transform.rotation = Quaternion.LerpUnclamped(currentRotation, recievedRotation, t);
        GM.Msg("UpdateDistance", ownerId, recievedPosition);
        //if (objType != "human") return;
        //var speed = (currentPosition - transform.position).magnitude;
    }

    /// <summary>
<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
    /// TODO: èª°ãŒã“ã‚Œã‚’é€ä¿¡ã™ã‚‹ã‹ã®æ±ºå®šãŒå¿…è¦
=======
    /// TODO: ï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ğ‘—Mï¿½ï¿½ï¿½é‚©ï¿½ÌŒï¿½ï¿½è‚ªï¿½Kï¿½v
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
    /// </summary>
    /// <param name="path"></param>
    public async void SetObject(string path)
    {
        var avatarObj = GM.Msg<GameObject>("LoadAvatar", path);
        SetContent(avatarObj.transform);

<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // IPFSã¸ã®Upload
=======
        // IPFSï¿½Ö‚ï¿½Upload
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        var cid = await GM.Msg<UniTask<string>>("UploadAvatar", path);
        this.cid = cid;
        GM.db.user.users[GM.db.rtc.id].cid = cid;

<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
        // å…¨ä½“ã¸ã®é€šçŸ¥
=======
        // ï¿½Sï¿½Ì‚Ö‚Ì’Ê’m
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
        var sendData = new Dictionary<string, object>()
        {
            { "type", "change" },
            { "objId",  objId },
            { "objType",  objType },
            { "cid", cid },
        };
        GM.Msg("RPCSendAll", sendData);
    }

    /// <summary>
<<<<<<< Updated upstream:Assets/Scripts/Core/Network/RTC/RTCObjectSync.cs
    /// Avatarç­‰ã‚’è¨­å®šã™ã‚‹
=======
    /// Avatarï¿½ï¿½ï¿½ï¿½İ’è‚·ï¿½ï¿½
>>>>>>> Stashed changes:Assets/Scripts/Core/RTC/RTCObject.cs
    /// </summary>
    /// <param name="obj"></param>
    public async void SetContent(Transform obj)
    {
        content.DestroyChildren();
        obj.SetParent(content);
        obj.ResetTransform();

        await UniTask.Yield();
        animator?.Rebind();
        animator?.Update(0f);
    }
}
